FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

# Copy everything (for first build); in docker-compose, we'll mount the code for live reload
COPY . .

EXPOSE 5123

CMD ["pnpm", "dev"]