version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: paymints-backend-dev
    ports:
      - "5123:5123"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: paymints-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: